apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
  labels:
    app: taqueria-bonjour
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '1'
      staleReplicaTimeout: '2880'
    volumeHandle: taqueria-bonjour-sqlite-volume
