apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
  labels:
    app: taqueria-bonjour
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: sqlite-pv
  storageClassName: longhorn
