FROM node:15.4.0-alpine3.10 as build

WORKDIR /src

# Build frontend
ENV PATH /src/node_modules/.bin:$PATH
COPY . ./
RUN yarn install
RUN yarn build

# Production slim container
FROM nginx:stable-alpine
LABEL org.opencontainers.image.source=https://github.com/paulkiernan/taqueria-bonjour
COPY --from=build /src/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
