FROM node:13.12.0-alpine as build

WORKDIR /src

ENV PATH /src/node_modules/.bin:$PATH
COPY package*.json ./
RUN npm install
RUN npm install react-scripts@3.4.1 -g
COPY . ./
RUN yarn build

# Production slim container
FROM nginx:stable-alpine
COPY --from=build /src/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
