apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    cert-manager.io/issuer-kind: ClusterIssuer
    field.cattle.io/description: Ingress for main personal website splash page
  name: taqueria-bonjour-ingress
  namespace: taqueria-bonjour
spec:
  rules:
  - host: bonjour.paulynomial.com
    http:
      paths:
      - backend:
          serviceName: taqueria-bonjour-service
          servicePort: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - bonjour.paulynomial.com
    secretName: taqueria-bonjour-ingress-prod-tls
