apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taqueria-bonjour-sqlite-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: taqueria-bonjour-sqlite-pv
  storageClassName: longhorn
